version: '3.8'

services:
  catalyst:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=docker
    volumes:
      - ./:/srv/catalyst
      - catalyst-repos:/srv/catalyst/repos
    depends_on:
      - locksmith
    networks:
      - app-network

  locksmith:
    build:
      context: https://github.com/mitanshu610/locksmith.git
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - ENVIRONMENT=docker
      - HOST=0.0.0.0
    volumes:
      - locksmith-repos:/srv/locksmith/repos
    networks:
      - app-network

  wayne:
    build:
      context: https://github.com/mitanshu610/wayne.git
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
      - ENVIRONMENT=docker
      - HOST-0.0.0.0
    volumes:
      - wayne-repos:/srv/wayne/repos
    depends_on:
      - catalyst
      - locksmith
    networks:
      - app-network

volumes:
  catalyst-repos:
  wayne-repos:
  locksmith-repos:

networks:
  app-network:
    driver: bridge
