# Server configuration
env: "local"
port: 8081
host: "localhost"
debug: true
app_name: "ai assistant"
use_dummy_user: True

# Database connections
db_url: "postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/cerebrum_os"
read_db_url: "postgresql+psycopg2://postgres:postgres@127.0.0.1:5432/cerebrum_os"
redis_payments_url: "redis://127.0.0.1:6379/4"

# External services
ingestion_url: "https://api.fexz0.de/service/almanac"

# API keys and credentials
openai_key: "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"
claude_key: "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"
groq_key: "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"
bing_search_api_key: "b3b8bb7e180a47518102c72296aebe9f"
bing_search_endpoint: "https://api.bing.microsoft.com/"
clerk_secret_key: "sk_test_aRZHMzYk1wWhF6DwOe9Pi7jts7zAd5ICLNHAnEimfg"
stream_token: "x-token-9f8a7c2bfa4e49bd83c6aef78b29c1d3"

# Kubernetes configuration
K8S_POD_NAME: "temp"

# Monitoring and logging
sentry_environment: "development"
frodo_sentry_dsn: ""


# Application settings
thread_summary_count: 10
full_message_count: 5
thread_summary_context_limit: 10000
use_thread_summaries: True
skip_paths_for_restriction: "/_readyz,/_healthz,/openapi.json,/v3.0/surface/1/models,/v2.0/surface/1/models,/metrics"
kb_agent_enabled: False